#!/usr/bin/env python3
"""Generate the LiveGamecode/ support files for ROM-free ("clean") builds.

In a live-gamecode build the app ships with NO recompiled game code. Instead,
weak forwarder functions satisfy every game-function symbol the app links
against (patches, overlay tables, the entrypoint), and dispatch into machine
code produced at runtime by N64Recomp's live recompiler from the user's ROM.

Inputs (all facts, no game content):
  - dump.toml                      symbol names/addresses/sizes
  - patches/*.c                    RECOMP_PATCH function names
  - n64recomp source symbol lists  which libultra names librecomp reimplements

Outputs (committed to the repo):
  - LiveGamecode/forwarders.c      weak forwarders for every game function
  - LiveGamecode/live_overrides.inl  vram -> patch-function table
  - LiveGamecode/funcs.h           declarations (copied from a generated set)
  - LiveGamecode/recomp_overlays.inl and lookup.cpp are copied from
    RecompiledFuncs by this script when available (they contain names/offsets
    only), so a machine that has run the full generation refreshes them.
"""
import re, glob, os, sys, shutil

os.chdir(os.path.dirname(os.path.abspath(__file__)))
os.makedirs("LiveGamecode", exist_ok=True)

# --- Load symbol sets from the N64Recomp source -------------------------------
SYMLIST_CANDIDATES = ["n64recomp-src/src/symbol_lists.cpp", "/root/ge/n64recomp/src/symbol_lists.cpp"]
symlist_src = None
for cand in SYMLIST_CANDIDATES:
    if os.path.exists(cand):
        symlist_src = open(cand).read()
        break
if symlist_src is None:
    sys.exit("cannot find N64Recomp symbol_lists.cpp")

def parse_set(name):
    m = re.search(rf"N64Recomp::{name}\s*{{(.*?)}};", symlist_src, re.S)
    return set(re.findall(r'"([^"]+)"', m.group(1))) if m else set()

reimplemented = parse_set("reimplemented_funcs")
ignored_builtin = parse_set("ignored_funcs")
renamed = parse_set("renamed_funcs")

# Config-level ignored/stubbed lists (keep in sync with us.toml)
def parse_toml_list(src, key):
    m = re.search(rf"{key} = \[\n(.*?)\n\]", src, re.S)
    return [s for s in re.findall(r'"([^"]+)"', m.group(1))] if m else []

us_toml = open("us.toml").read()
config_ignored = set(parse_toml_list(us_toml, "ignored"))
config_stubs = set(parse_toml_list(us_toml, "stubs"))

# --- Parse dump.toml functions ------------------------------------------------
dump = open("dump.toml").read()
funcs = []  # (name, vram)
for m in re.finditer(r'\{ name = "(\w+)", vram = (0x[0-9A-Fa-f]+), size = (0x[0-9A-Fa-f]+) \}', dump):
    if int(m.group(3), 16) > 0:
        funcs.append((m.group(1), int(m.group(2), 16)))

seen = set()
uniq = []
for name, vram in funcs:
    if name not in seen:
        seen.add(name)
        uniq.append((name, vram))
funcs = uniq
print(f"{len(funcs)} named functions in dump.toml")

# --- Patch function names: use what the patches pipeline ACTUALLY emitted -----
# (a RECOMP_PATCH in the sources does not guarantee an emitted override; trusting
#  the sources once produced an override pointing at our own forwarder = livelock)
patched = set()
patches_c = "RecompiledPatches/patches.c"
if not os.path.exists(patches_c):
    sys.exit("RecompiledPatches/patches.c not found — build the patches first")
for m in re.finditer(r"RECOMP_FUNC void ([A-Za-z_][A-Za-z0-9_]*)\(uint8_t\* rdram", open(patches_c).read()):
    patched.add(m.group(1))
print(f"{len(patched)} emitted patch functions")

by_name = dict(funcs)
missing = [p for p in patched if p not in by_name]
if missing:
    print(f"WARNING: patched but not in dump.toml (new functions?): {sorted(missing)}")

# --- forwarders.c -------------------------------------------------------------
out = []
out.append('// Autogenerated by tools_gen_live.py — weak forwarders into live-recompiled code.')
out.append('#include "recomp.h"')
out.append('void live_call(unsigned int vram, uint8_t* rdram, recomp_context* ctx);')
out.append("")
count = 0
for name, vram in funcs:
    if name in reimplemented or name in ignored_builtin or name in config_ignored:
        continue  # librecomp provides these (as name_recomp), or they are dead code
    final = name + "_recomp" if name in renamed else name
    out.append(f'RECOMP_FUNC __attribute__((weak)) void {final}(uint8_t* rdram, recomp_context* ctx) {{ live_call(0x{vram:08X}u, rdram, ctx); }}')
    count += 1
open("LiveGamecode/forwarders.c", "w").write("\n".join(out) + "\n")
print(f"forwarders.c: {count} forwarders")

# --- live_overrides.inl -------------------------------------------------------
ov = []
ov.append('// Autogenerated by tools_gen_live.py — vram -> strong patch symbol overrides.')
ov.append('// Included by live_gamecode.cpp.')
entries = []
for p in sorted(patched):
    if p in by_name:
        ov.append(f'extern "C" void {p}(uint8_t* rdram, recomp_context* ctx);')
        entries.append((by_name[p], p))
ov.append("")
ov.append("static const LiveOverride live_override_list[] = {")
for vram, name in sorted(entries):
    ov.append(f'    {{ 0x{vram:08X}u, {name} }},')
ov.append("};")
# Shims that librecomp/ultramodern provide for libultra functions. Only emit
# entries for symbols that are ACTUALLY defined: declaring an undefined symbol
# and letting it resolve to null works with GNU ld but is a hard link error with
# Apple's ld64 ("symbol(s) not found for architecture arm64").
defined_shims = set()
shim_sources = (glob.glob("lib/N64ModernRuntime/librecomp/src/*.cpp") +
                glob.glob("lib/N64ModernRuntime/ultramodern/src/*.cpp"))
for path in shim_sources:
    for m in re.finditer(r'extern\s+"C"\s+void\s+(\w+_recomp)\s*\([^)]*\)\s*\{', open(path).read()):
        defined_shims.add(m.group(1))
print(f"{len(defined_shims)} libultra shims defined by the runtime")

shim_names = []
for name, vram in funcs:
    if (name in reimplemented or name in ignored_builtin) and (name + "_recomp") in defined_shims:
        shim_names.append((vram, name + "_recomp"))
for vram, n in shim_names:
    ov.append(f'extern "C" void {n}(uint8_t* rdram, recomp_context* ctx);')
ov.append("")
ov.append("static const LiveOverride live_shim_list[] = {")
for vram, n in sorted(shim_names):
    ov.append(f'    {{ 0x{vram:08X}u, {n} }},')
ov.append("};")

# vrams the cosf-fallthrough shim needs
if "cosf" in by_name and "sinf" in by_name:
    ov.append(f"#define GE_COSF_VRAM 0x{by_name['cosf']:08X}u")
    ov.append(f"#define GE_SINF_VRAM 0x{by_name['sinf']:08X}u")
open("LiveGamecode/live_overrides.inl", "w").write("\n".join(ov) + "\n")
print(f"live_overrides.inl: {len(entries)} overrides")

# --- Copy the facts-only generated files if a full generation exists ----------
for f in ("funcs.h", "recomp_overlays.inl", "lookup.cpp"):
    src = os.path.join("RecompiledFuncs", f)
    if os.path.exists(src):
        shutil.copy(src, os.path.join("LiveGamecode", f))
        print(f"refreshed LiveGamecode/{f}")
