// Autogenerated by tools_gen_live.py — vram -> strong patch symbol overrides.
// Included by live_gamecode.cpp.
extern "C" void __scMain(uint8_t* rdram, recomp_context* ctx);
extern "C" void bgScissorCurrentPlayerView(uint8_t* rdram, recomp_context* ctx);
extern "C" void bgUpdateCurrentPlayerScreenMinMax(uint8_t* rdram, recomp_context* ctx);
extern "C" void bossMainloop(uint8_t* rdram, recomp_context* ctx);
extern "C" void currentPlayerDrawFade(uint8_t* rdram, recomp_context* ctx);
extern "C" void getPlayer_c_lodscalez(uint8_t* rdram, recomp_context* ctx);
extern "C" void getinstsize(uint8_t* rdram, recomp_context* ctx);
extern "C" void init(uint8_t* rdram, recomp_context* ctx);
extern "C" void interface_menu00_legalscreen(uint8_t* rdram, recomp_context* ctx);
extern "C" void joyRumblePakInit(uint8_t* rdram, recomp_context* ctx);
extern "C" void modelSetDistanceDisabled(uint8_t* rdram, recomp_context* ctx);
extern "C" void musicTrack1Play(uint8_t* rdram, recomp_context* ctx);
extern "C" void musicTrack2Play(uint8_t* rdram, recomp_context* ctx);
extern "C" void musicTrack3Play(uint8_t* rdram, recomp_context* ctx);
extern "C" void renderGunbarrelEyeIntroSequence(uint8_t* rdram, recomp_context* ctx);
extern "C" void rmonCreateThread(uint8_t* rdram, recomp_context* ctx);
extern "C" void select_ramrom_to_play(uint8_t* rdram, recomp_context* ctx);
extern "C" void skyRenderFull(uint8_t* rdram, recomp_context* ctx);
extern "C" void skyRenderTri(uint8_t* rdram, recomp_context* ctx);
extern "C" void titleRenderFolderMenuBackgroundLines(uint8_t* rdram, recomp_context* ctx);
extern "C" void zbufClearCurrentPlayer(uint8_t* rdram, recomp_context* ctx);

static const LiveOverride live_override_list[] = {
    { 0x800004A0u, init },
    { 0x80000640u, rmonCreateThread },
    { 0x80000BB0u, __scMain },
    { 0x80005E60u, bossMainloop },
    { 0x80006C7Cu, musicTrack1Play },
    { 0x80007004u, musicTrack2Play },
    { 0x8000738Cu, musicTrack3Play },
    { 0x8000B534u, joyRumblePakInit },
    { 0x80409254u, renderGunbarrelEyeIntroSequence },
    { 0x8040A6DCu, interface_menu00_legalscreen },
    { 0x8041B240u, titleRenderFolderMenuBackgroundLines },
    { 0x8046C400u, modelSetDistanceDisabled },
    { 0x8046D00Cu, getinstsize },
    { 0x80478484u, getPlayer_c_lodscalez },
    { 0x804804E0u, currentPlayerDrawFade },
    { 0x80497818u, skyRenderTri },
    { 0x80498A2Cu, skyRenderFull },
    { 0x804B5058u, bgScissorCurrentPlayerView },
    { 0x804B908Cu, bgUpdateCurrentPlayerScreenMinMax },
    { 0x804C0970u, select_ramrom_to_play },
    { 0x804D2518u, zbufClearCurrentPlayer },
};
extern "C" void osDpSetNextBuffer_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViBlack_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osContGetReadData_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osContGetQuery_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osStartThread_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __ull_rem_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __osPiRelAccess_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViGetCurrentFramebuffer_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osDestroyThread_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osCreateMesgQueue_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osEepromLongRead_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osAiGetLength_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osGetCount_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osCreatePiManager_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osEepromLongWrite_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osCreateThread_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osVirtualToPhysical_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osMotorInit_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osRecvMesg_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSendMesg_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSetEventMesg_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osPiGetStatus_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osPiRawStartDma_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViSetMode_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __ull_to_f_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __ull_to_d_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osContStartQuery_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViSetXScale_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSetThreadPri_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osPiStartDma_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSpTaskYield_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSpTaskYielded_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osInvalICache_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSpTaskLoad_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osMotorStart_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osJamMesg_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSpTaskStartGo_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osWritebackDCacheAll_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSetTimer_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osAiSetFrequency_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osContInit_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViSetSpecialFeatures_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViSwapBuffer_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osEPiRawStartDma_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osPfsChecker_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViSetYScale_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osAiSetNextBuffer_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osGetThreadPri_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osStopThread_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __ull_div_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViRepeatLine_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osInitialize_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osEepromWrite_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViSetEvent_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __osSpSetPc_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osEepromRead_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __osPiGetAccess_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __ll_mul_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __ll_div_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osGetTime_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osDpSetStatus_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osCreateViManager_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osMotorStop_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osContStartReadData_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osYieldThread_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osViGetNextFramebuffer_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osEepromProbe_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osInvalDCache_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __osSetFpcCsr_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osSetIntMask_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void osWritebackDCache_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __osDisableInt_recomp(uint8_t* rdram, recomp_context* ctx);
extern "C" void __osRestoreInt_recomp(uint8_t* rdram, recomp_context* ctx);

static const LiveOverride live_shim_list[] = {
    { 0x8000B528u, osPfsChecker_recomp },
    { 0x8000C780u, osMotorStop_recomp },
    { 0x8000C8ACu, osMotorStart_recomp },
    { 0x8000CB38u, osMotorInit_recomp },
    { 0x8000CD90u, osPiRawStartDma_recomp },
    { 0x8000CE70u, osPiGetStatus_recomp },
    { 0x8000CE80u, osInitialize_recomp },
    { 0x8000D120u, osWritebackDCacheAll_recomp },
    { 0x8000D150u, osInvalICache_recomp },
    { 0x8000D220u, __osSetFpcCsr_recomp },
    { 0x8000D230u, osCreateThread_recomp },
    { 0x8000D380u, osStartThread_recomp },
    { 0x8000D4D0u, osCreateMesgQueue_recomp },
    { 0x8000D540u, osStopThread_recomp },
    { 0x8000D600u, osSetThreadPri_recomp },
    { 0x8000D6E0u, osGetCount_recomp },
    { 0x8000D6F0u, osCreateViManager_recomp },
    { 0x8000DA50u, osSetEventMesg_recomp },
    { 0x8000DAC0u, osViSetEvent_recomp },
    { 0x8000DB30u, osSetIntMask_recomp },
    { 0x8000DBD0u, osRecvMesg_recomp },
    { 0x8000DD10u, osSendMesg_recomp },
    { 0x8000DE60u, osViSetMode_recomp },
    { 0x8000DED0u, osViSetXScale_recomp },
    { 0x8000E000u, osViSetYScale_recomp },
    { 0x8000E060u, osViRepeatLine_recomp },
    { 0x8000E0D0u, osViBlack_recomp },
    { 0x8000E140u, osSpTaskYielded_recomp },
    { 0x8000E210u, osViGetCurrentFramebuffer_recomp },
    { 0x8000E250u, osViGetNextFramebuffer_recomp },
    { 0x8000E290u, osViSwapBuffer_recomp },
    { 0x8000E2E0u, osDpSetStatus_recomp },
    { 0x8000E40Cu, osSpTaskLoad_recomp },
    { 0x8000E56Cu, osSpTaskStartGo_recomp },
    { 0x8000E5B0u, osDpSetNextBuffer_recomp },
    { 0x8000E660u, osSpTaskYield_recomp },
    { 0x8000E6B0u, osVirtualToPhysical_recomp },
    { 0x8000E730u, osAiSetFrequency_recomp },
    { 0x8000E9B0u, osGetTime_recomp },
    { 0x8000EA6Cu, __ull_rem_recomp },
    { 0x8000EAA8u, __ull_div_recomp },
    { 0x8000EB4Cu, __ll_div_recomp },
    { 0x8000EBA8u, __ll_mul_recomp },
    { 0x8000ED00u, osAiSetNextBuffer_recomp },
    { 0x8000EDB0u, osAiGetLength_recomp },
    { 0x8000F4A0u, osPiStartDma_recomp },
    { 0x8000F5B0u, osViSetSpecialFeatures_recomp },
    { 0x800108D0u, osYieldThread_recomp },
    { 0x80010920u, osInvalDCache_recomp },
    { 0x800109D0u, osWritebackDCache_recomp },
    { 0x80010A50u, osSetTimer_recomp },
    { 0x800143B0u, osCreatePiManager_recomp },
    { 0x80014700u, osContInit_recomp },
    { 0x80014AC0u, osContStartQuery_recomp },
    { 0x80014B44u, osContGetQuery_recomp },
    { 0x80014B70u, osContStartReadData_recomp },
    { 0x80014C34u, osContGetReadData_recomp },
    { 0x80014DD0u, osEepromProbe_recomp },
    { 0x80014E40u, osEepromRead_recomp },
    { 0x80015140u, osEepromWrite_recomp },
    { 0x80015620u, osEepromLongRead_recomp },
    { 0x80015760u, osEepromLongWrite_recomp },
    { 0x800178B4u, __ull_to_d_recomp },
    { 0x800178E8u, __ull_to_f_recomp },
    { 0x800183F0u, __osDisableInt_recomp },
    { 0x80018410u, __osRestoreInt_recomp },
    { 0x80018830u, osGetThreadPri_recomp },
    { 0x80018CF0u, __osSpSetPc_recomp },
    { 0x8001B4B0u, osJamMesg_recomp },
    { 0x8001B960u, osDestroyThread_recomp },
    { 0x8001D560u, __osPiGetAccess_recomp },
    { 0x8001D5A4u, __osPiRelAccess_recomp },
    { 0x8001E330u, osEPiRawStartDma_recomp },
};
#define GE_COSF_VRAM 0x80457EA0u
#define GE_SINF_VRAM 0x80457EACu
